In [ ]:
import numpy

In [ ]:
pip install numpy

In [1]:
import numpy

In [3]:
import numpy as li

In [38]:
a=li.array([(2,4,6,8),(1,3,7,9),(9,8,7,6)])

In [39]:
print(a)

[[2 4 6 8]
 [1 3 7 9]
 [9 8 7 6]]


In [40]:
trans=li.transpose(a)

In [41]:
print(trans)

[[2 1 9]
 [4 3 8]
 [6 7 7]
 [8 9 6]]


In [42]:
trans=li.ravel(a)

In [44]:
print(trans)

[2 4 6 8 1 3 7 9 9 8 7 6]


In [46]:
a.reshape(1,12)

array([[2, 4, 6, 8, 1, 3, 7, 9, 9, 8, 7, 6]])

In [47]:
a.reshape(12,1)

array([[2],
       [4],
       [6],
       [8],
       [1],
       [3],
       [7],
       [9],
       [9],
       [8],
       [7],
       [6]])

In [56]:
a=li.zeros((5,14))

In [57]:
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [58]:
li.random.random((5,5))

array([[0.54882952, 0.27290566, 0.29039347, 0.01313437, 0.33252554],
       [0.84682732, 0.84111415, 0.11519678, 0.49193272, 0.87934962],
       [0.29273377, 0.7702487 , 0.86852617, 0.7842648 , 0.53035222],
       [0.2461386 , 0.53147455, 0.85664937, 0.78425242, 0.19783464],
       [0.24445726, 0.30018515, 0.43888801, 0.67321067, 0.47276148]])