In [ ]:
import numpy

In [ ]:
pip install numpy

In [1]:
import numpy

In [3]:
import numpy as li

In [38]:
a=li.array([(2,4,6,8),(1,3,7,9),(9,8,7,6)])

In [39]:
print(a)

[[2 4 6 8]
 [1 3 7 9]
 [9 8 7 6]]


In [40]:
trans=li.transpose(a)

In [41]:
print(trans)

[[2 1 9]
 [4 3 8]
 [6 7 7]
 [8 9 6]]


In [42]:
trans=li.ravel(a)

In [44]:
print(trans)

[2 4 6 8 1 3 7 9 9 8 7 6]


In [46]:
a.reshape(1,12)

array([[2, 4, 6, 8, 1, 3, 7, 9, 9, 8, 7, 6]])

In [47]:
a.reshape(12,1)

array([[2],
       [4],
       [6],
       [8],
       [1],
       [3],
       [7],
       [9],
       [9],
       [8],
       [7],
       [6]])

In [56]:
a=li.zeros((5,14))

In [57]:
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [59]:
li.random.random((7,7))

array([[0.769167  , 0.25194894, 0.04847575, 0.8756312 , 0.11616647,
        0.62035987, 0.62485812],
       [0.96149407, 0.96056859, 0.77476983, 0.62175578, 0.50552304,
        0.95367088, 0.83788587],
       [0.88906331, 0.05893751, 0.82770977, 0.39505143, 0.1206891 ,
        0.84386562, 0.84999306],
       [0.98016198, 0.20100572, 0.87398394, 0.82725421, 0.00534254,
        0.25296012, 0.16310523],
       [0.05251298, 0.36236146, 0.00148179, 0.1753585 , 0.59742305,
        0.88701346, 0.9254943 ],
       [0.53668057, 0.546522  , 0.47992219, 0.15528062, 0.93050357,
        0.9054312 , 0.03862773],
       [0.30548342, 0.33553037, 0.2134845 , 0.46783371, 0.65578679,
        0.54188082, 0.61972047]])